name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69ebb7b10fd47ff4a3963790587249a1818ff0d47c939f6f08ab60ddf30e9008"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
