name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90a7a24ab722439c25c6f8928a94657bd948e38b8b20cd16c2a401cb5304113f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
