name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b1fa100d08ab6ed23dacecb6f1f44f479765a25a0427dcec07f57c087c37e28"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
