name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4522314a5967d67563e3910bf2b78d978f0888f342a5601a3015efb0fb1fdc76"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
