name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "871050af2e3f9e3a5af5285483a4452f22d36d6ccb59e28254c715e416e68e09"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
