name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a4af5e5fb955fa9257c8a07efdff6a77ebacb319636baf2706314b084bd9f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
