name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccf307cf4b65c9e63553906e1b370289c2ac90b814d4c01acdd81680ceb8eece"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
