name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e62d9ea80710189258e3038d05eb7d46289c88216b463e60e9f1b03ff9802ff"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
