name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b16aa747edbc4231385ddf931b6dd0aa174b93c09e5a6ab87099f8cfcf8d750"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
