name = "Create"
author = "Lars van Dartel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0cdf912b2d911c968b7c34c9e22cde88dd328743c100b7affd367638f602270"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
