name: build client
on:
  push:
    paths:
      # Run when multimc client files are changed
      - multimc-files/**
  workflow_dispatch:

jobs:
  build-client:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: larsvandartel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: build
      run: nix build .#client-instance

    - name: upload
      uses: actions/upload-artifact@v4
      if: github.ref_type != 'tag'
      with:
        name: client
        path: result/*.zip

    - name: release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files:
          result/*.zip
