name: update mods
on:
  schedule:
    # run each day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-mods:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: larsvandartel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: update
      run: nix run nixpkgs#packwiz -- update --all -y

    - name: commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "chore: update mods"
