name: update mods
on:
  schedule:
    # run each day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-mods:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: larsvandartel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: update
      run: nix run nixpkgs#packwiz -- update --all -y

    - name: create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "chore: update mods"
        branch: "chore/update"
        title: "chore: update mods"
        body:
